Fix wrong child block type choice
sonata-project/SonataBlockBundle pull request #873
Opened 2021-04-08 12:29 UTC by gremo

## Subject

I am targeting this branch, because this is a bugfix.

It should be safe and BC because this bundle requires Symfony 4 which uses keys as labels and values as values in the choice type field.  `ServiceListType` seems to be used only in [`BlockAdmin`](https://github.com/sonata-project/SonataPageBundle/blob/3.x/src/Admin/BlockAdmin.php#L180).

Closes #872

## Changelog

```markdown
### Added
- Flipped `ServiceListType` returned `choices` option
```

2021-04-08 19:04 UTC, core23 approved these changes

2021-04-08 19:54 UTC, VincentLanglet requested changes
IMHO it's better to directly set the right key and the right value.

It would avoid some duplicate keys/values issues.

2021-04-08 19:54 UTC, VincentLanglet commented on src/Form/Type/ServiceListType.php
>                      $types[$code] = sprintf('%s - %s', $service->getName(), $code);
```suggestion
                    $label = sprintf('%s - %s', $service->getName(), $code);
                    $types[$label] = $code;
```

2021-04-08 20:13 UTC, gremo commented on src/Form/Type/ServiceListType.php
>                      $types[$code] = sprintf('%s - %s', $service->getName(), $code);
Done sir!

2021-04-08 20:45 UTC, VincentLanglet approved these changes

2021-04-09 05:37 UTC, jordisala1991 approved these changes

2021-04-09 05:37 UTC, merged

2021-04-09 05:37 UTC, jordisala1991 commented
Thank you @gremo

2021-04-30 10:50 UTC, gremo commented
Can we have a release for the 3.x branch?

2021-04-30 11:24 UTC, VincentLanglet commented
@OskarStark No release are needed for BlockBundle 3.x in https://d5zda2diva-x6miu6vkqhzpi.eu.s5y.io/next-releases

And `bin/console release` is returning `[WARNING] Release is not needed`

2021-05-24 11:24 UTC, gremo commented
Sorry to bother, do you still have problems with releases?

2021-05-24 12:29 UTC, VincentLanglet commented
https://github.com/sonata-project/SonataBlockBundle/releases/tag/3.23.1

2021-05-24 12:42 UTC, gremo commented
Sorry, didn't see that :)