Deprecate BlockManagerInterface
sonata-project/SonataBlockBundle pull request #958
Opened 2021-10-08 14:38 UTC by core23

## Subject

I am targeting this branch, because this interface is not used anywhere.

## Changelog

```markdown
### Deprecated
- Deprecate `Sonata\BlockBundle\Model\BlockManagerInterface`
```

2021-10-08 14:46 UTC, VincentLanglet commented on composer.json
> +        "sonata-project/doctrine-extensions": "^1.10.1",
Can we remove totally the dependency ? If not, will we be able to do it in next major ?

2021-10-08 14:48 UTC, core23 commented on composer.json
> +        "sonata-project/doctrine-extensions": "^1.10.1",
We still need this for phpstan / psalm, because it is imported in the deprecated class.

2021-10-08 15:01 UTC, VincentLanglet commented on composer.json
> +        "sonata-project/doctrine-extensions": "^1.10.1",
Ok, so we're be able to remove the dependancy in the next major ; should we add a reminder ?

2021-10-08 15:01 UTC, VincentLanglet submitted a review, later dismissed

2021-10-08 16:08 UTC, core23 commented on composer.json
> +        "sonata-project/doctrine-extensions": "^1.10.1",
I'll do this once the dev-kit job merges this to the 5.x branch

2021-10-09 06:30 UTC, jordisala1991 commented
https://github.com/search?q=org%3Asonata-project+BlockManagerInterface&type=code

This interface is used on SonataPageBundle

2021-10-09 07:44 UTC, core23 commented
> This interface is used on SonataPageBundle

But there is no usage and implementation in *this* project. We should move the interface to the `SonataPageBundle`.

2021-10-09 08:02 UTC, VincentLanglet approved these changes

2021-10-09 10:01 UTC, VincentLanglet requested changes
After more thought I'm not sure about removing the doctrine-extensions from the require section.
Someone using the BlockManagerInterface will have the project crashing if he didn't required the doctrine-extensions package. And he has no reason to do it since it doesn't use it directly...

I feel like it safer to keep it in the require section for this major

2021-10-09 10:17 UTC, core23 commented
> After more thought I'm not sure about removing the doctrine-extensions from the require section.
> Someone using the BlockManagerInterface will have the project crashing if he didn't required the doctrine-extensions package. And he has no reason to do it since it doesn't use it direct

That's a problem for all optional dependencies we have....

IMHO there are only two case for someone using the `BlockManagerInterface`:
- they should either use the `SonataPageBundle` (which requires the optional dependency) 
- there is a custom project implementation for the interface. This project should then require the `sonata-project/doctrine-extensions` inside the `composer.json` file

2021-10-09 10:23 UTC, VincentLanglet commented
> > After more thought I'm not sure about removing the doctrine-extensions from the require section.
> > Someone using the BlockManagerInterface will have the project crashing if he didn't required the doctrine-extensions package. And he has no reason to do it since it doesn't use it direct
> 
> That's a problem for all optional dependencies we have....

The issue here is that `doctrine-extensions` wasn't considered as an optional dependency before.
Changing his state from `required` to `optional` is the BC-break I point out.
I don't think it's an issue to keep it in the require section until we remove the dependency... is it ?

> IMHO there are only two case for someone using the `BlockManagerInterface`:
> 
> * there is a custom project implementation for the interface. This project should then require the `sonata-project/doctrine-extensions` inside the `composer.json` file

Dunno what others @sonata-project/contributors thinks about this BC-break.
But if we accepts this, it should be at least in the changelog/upgrade section.

2021-10-09 11:01 UTC, jordisala1991 commented
> > > After more thought I'm not sure about removing the doctrine-extensions from the require section.
> 
> > > Someone using the BlockManagerInterface will have the project crashing if he didn't required the doctrine-extensions package. And he has no reason to do it since it doesn't use it direct
> 
> > 
> 
> > That's a problem for all optional dependencies we have....
> 
> 
> 
> The issue here is that `doctrine-extensions` wasn't considered as an optional dependency before.
> 
> Changing his state from `required` to `optional` is the BC-break I point out.
> 
> I don't think it's an issue to keep it in the require section until we remove the dependency... is it ?
> 
> 
> 
> > IMHO there are only two case for someone using the `BlockManagerInterface`:
> 
> > 
> 
> > * there is a custom project implementation for the interface. This project should then require the `sonata-project/doctrine-extensions` inside the `composer.json` file
> 
> 
> 
> Dunno what others @sonata-project/contributors thinks about this BC-break.
> 
> But if we accepts this, it should be at least in the changelog/upgrade section.
> 
> 

My main concern would be about providing the required migration path for other bundles using this class before declaring it deprecated.

2021-10-11 09:43 UTC, core23 commented
> My main concern would be about providing the required migration path for other bundles using this class before declaring it deprecated.

There is no migration path, because this bundle does not provide any implementation for this method.

This [PR](https://github.com/sonata-project/SonataPageBundle/pull/1369) adds the interface to the only bundle that is implementing the interface.

2021-10-14 07:44 UTC, VincentLanglet commented on composer.json
> -        "sonata-project/doctrine-extensions": "^1.10.1",
Please review @sonata-project/contributors 

Does moving a require to a require-dev is a BC-break ?

2021-10-28 08:41 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2021-10-28 09:31 UTC, core23 commented on composer.json
> -        "sonata-project/doctrine-extensions": "^1.10.1",
Ping @sonata-project/contributors

2021-10-28 09:35 UTC, dmaicher commented on composer.json
> -        "sonata-project/doctrine-extensions": "^1.10.1",
I don't think we should cover this under our BC promises. If someone is relying on this package then they need to require it explicitly, or?

2021-10-28 09:49 UTC, VincentLanglet commented on composer.json
> -        "sonata-project/doctrine-extensions": "^1.10.1",
But here you may need it without relying on this package directly.
If you were using Sonata\BlockBundle\Model\BlockManagerInterface, you'll need the dependency.

2021-11-01 11:43 UTC, core23 commented on composer.json
> -        "sonata-project/doctrine-extensions": "^1.10.1",
Move this to a new PR: https://github.com/sonata-project/SonataBlockBundle/pull/971

2021-11-01 12:22 UTC, VincentLanglet approved these changes

2021-11-01 13:03 UTC, merged